### ISSUE TITLE
日記内容の編集機能の実装

### ISSUE THREAD

**Issue by mtwt127** [mtwt127/qol-daily#20]
・消去ボタンのような、編集ボタンを実装
・/daily/:idに移動して、追加画面のように日記内容を修正できるようにする
・可能であればcreate_atは編集されないように
・可能であれば直前の日記の内容は編集ページで表示されるようにしたい

**Comment by mtwt127** [comment]
/daily/editに移動して、日記内容を入力させるところまで実装完了

**Comment by mtwt127** [comment]
edit画面での@postに選択したpostをcontrollerで代入したい

@post = Post.find(params[:id])
これをeditアクションに記入するだけではエラーになる。

**Comment by mtwt127** [comment]
最低限の実装機能は実現した。
但し、いくつかの問題点はあるので書いておく

・編集画面で前の日記の内容が確認できない
・更新ボタン押下時に、次のようなエラーログが出力される(ただし更新は出来る)
Started PATCH "/daily/30" for ::1 at 2024-07-09 15:30:45 +0900
Processing by PostsController#editDaily as TURBO_STREAM
  Parameters: {"authenticity_token"=>"[FILTERED]", "title"=>"22", "body"=>"33", "qol"=>"33", "commit"=>"投稿", "id"=>"30"}
  Post Load (0.2ms)  SELECT "posts".* FROM "posts" WHERE "posts"."id" = ? LIMIT ?  [["id", 30], ["LIMIT", 1]]
  ↳ app/controllers/posts_controller.rb:19:in `editDaily'
Unpermitted parameters: :_method, :authenticity_token, :commit, :id. Context: { controller: PostsController, action: editDaily, request: #<ActionDispatch::Request:0x00007f016cef1e28>, params: {"_method"=>"patch", "authenticity_token"=>"[FILTERED]", "title"=>"22", "body"=>"33", "qol"=>"33", "commit"=>"投稿", "controller"=>"posts", "action"=>"editDaily", "id"=>"30"} }
  TRANSACTION (0.1ms)  begin transaction
  ↳ app/controllers/posts_controller.rb:20:in `editDaily'
  Post Update (5.8ms)  UPDATE "posts" SET "title" = ?, "body" = ?, "qol" = ?, "updated_at" = ? WHERE "posts"."id" = ?  [["title", "22"], ["body", "33"], ["qol", 33], ["updated_at", "2024-07-09 06:30:46.037775"], ["id", 30]]
  ↳ app/controllers/posts_controller.rb:20:in `editDaily'
  TRANSACTION (0.2ms)  commit transaction
  ↳ app/controllers/posts_controller.rb:20:in `editDaily'
Redirected to http://localhost:3000/daily
Completed 302 Found in 118ms (ActiveRecord: 8.4ms | Allocations: 23160)

**Comment by mtwt127** [comment]
提出期限まで実装時間が残っていない&機能面で特に問題は無いためマージをする。
